# 使用原始镜像ubuntu:14.04;执行apt update && apt install make;添加当前目录下gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz到/opt下；在/usr/local/bin创建软链接，链接解压目录下bin中的gcc和g++；删除导入的压缩文件；添加当前目录下的cmake-3.20.2-linux-x86_64.tar.gz到/opt；在/usr/local/bin创建软链接，链接解压目录下bin中的cmake;删除导入的压缩文件。执行gcc -v;执行cmake --version;
FROM ubuntu:14.04
LABEL autor="wangjian"
LABEL maintainer="656876071@qq.com"
LABEL description="Dockerfile for arm-linux-gnueabihf"
LABEL from="ubuntu14.04"
LABEL cmake="3.20.6"
LABEL version="1.0.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make \
    build-essential \
    wget \
    tar \
    xz-utils \
    python \
    ca-certificates \
    libncurses5-dev

# 解压 .tar.gz 到 /opt/
RUN wget https://cmake.org/files/v3.20/cmake-3.20.6.tar.gz \
 && tar -xf cmake-3.20.6.tar.gz \
 && mv cmake-3.20.6 /opt/cmake

# 创建 cmake 软链接（注意解压后的目录名）
# RUN ln -s /opt/cmake-3.20.6/bin/cmake /usr/local/bin/cmake

# 环境变量 （=分割新格式）
ENV PATH=/opt/cmake/bin:$PATH
# 验证
RUN cmake --version


