FROM ubuntu:14.04
LABEL autor="wangjian"
LABEL maintainer="656876071@qq.com"
LABEL org.opencontainers.image.description DESCRIPTION="Dockerfile for arm-linux-gnueabihf common image"
LABEL from="ubuntu14.04"
LABEL cmake="3.20.6"
LABEL version="1.0.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make \
    build-essential \
    wget \
    tar \
    xz-utils \
    python \
    ca-certificates \
    libncurses5-dev

# 解压 .tar.gz 到 /opt/
RUN wget https://cmake.org/files/v3.20/cmake-3.20.6-linux-x86_64.tar.gz \
 && tar -xf cmake-3.20.6-linux-x86_64.tar.gz \
 && mv cmake-3.20.6-linux-x86_64 /opt/cmake

# 创建 cmake 软链接（注意解压后的目录名）
# RUN ln -s /opt/cmake-3.20.6-linux-x86_64/bin/cmake /usr/local/bin/cmake

# 环境变量 （=分割新格式）
ENV PATH=/opt/cmake/bin:$PATH
# 验证
RUN cmake --version






