FROM ubuntu:22.04
LABEL autor="wangjian"
LABEL maintainer="656876071@qq.com"
LABEL org.opencontainers.image.description="Dockerfile for buildroot common image"
LABEL from="ubuntu22.04"
LABEL version="1.0.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git ssh make gcc libssl-dev \
    liblz4-tool expect expect-dev g++ patchelf chrpath gawk texinfo chrpath \
    diffstat binfmt-support qemu-user-static live-build bison flex fakeroot \
    cmake gcc-multilib g++-multilib unzip device-tree-compiler ncurses-dev \
    libgucharmap-2-90-dev bzip2 expat gpgv2 cpp-aarch64-linux-gnu libgmp-dev \
    libmpc-dev bc python-is-python3 python2 curl file rsync bsdmainutils

RUN ln -sf /usr/bin/python2 /usr/bin/python

