FROM ghcr.io/ezioswj/toolchain/arm/am335x/common:latest
LABEL autor="wangjian"
LABEL maintainer="656876071@qq.com"
LABEL org.opencontainers.image.description="Dockerfile for arm-linux-gnueabihf common image with gcc4.9"
LABEL from="ubuntu14.04"
LABEL gcc="gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf"
LABEL cmake="3.20.6"
LABEL version="1.0.0"

ENV DEBIAN_FRONTEND=noninteractive

# ADD 自动解压 .tar.xz 到 /opt/
RUN wget https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/arm-linux-gnueabihf/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
RUN tar -xf gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf.tar.xz && mv gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf /opt/gcc
##############
RUN ls /opt/gcc
RUN ls /opt/gcc/bin
##############

# 环境变量 （=分割新格式）
ENV PATH=/opt/gcc/bin:$PATH

# 验证
RUN arm-linux-gnueabihf-gcc -v
